Iter9
lev-stas/metricsmonitor pull request #10
Opened 2023-12-03 12:09 UTC by lev-stas

2023-12-03 17:50 UTC, maxlyaptsev requested changes

2023-12-03 18:56 UTC, lev-stas commented on internal/agentrunners/reportrunner.go
> +		_, er := client.R().
Вынес создание клиента на уровень выше

2023-12-03 18:59 UTC, lev-stas commented on internal/handlers/updatehandler.go
> +		}
Убрал проверку

2023-12-03 19:45 UTC, lev-stas commented on internal/handlers/updatehandler.go
> +			storage.SetCounterMetric(metric.ID, *metric.Delta)
Поменял названия методов

2023-12-03 20:06 UTC, lev-stas commented on internal/handlers/valuehandler.go
> +		} else if metric.MType == "counter" {
Вынес обработку запросов с uri параметрами в два отдельных файла

2023-12-04 17:34 UTC, lev-stas commented on internal/metricsstorage/filewriter.go
> +package metricsstorage
Сдела тест для записи

2023-12-05 14:55 UTC, lev-stas commented on internal/metricsstorage/filewriter.go
> +	file, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE, 0666)
Оставил файл открытым если у нас выставлено синхронное сохранение

2023-12-05 14:56 UTC, lev-stas commented on internal/metricsstorage/metricsreader.go
> +	file, err := os.OpenFile(filename, os.O_RDONLY|os.O_CREATE, 0666)
Открытие файла вынес в метод

2023-12-05 14:56 UTC, lev-stas commented on internal/metricsstorage/filewriter.go
> +}
Оставили метод на случай закрытия файла при завершении работы приложения.

2023-12-06 16:52 UTC, lev-stas commented on cmd/server/main.go
> +	if configs.ServerParams.Restore {
Вынес создание Reader-a в отдельный блок

2023-12-06 16:52 UTC, lev-stas commented on internal/handlers/updatehandler.go
> +			fileWriter, er := metricsstorage.NewFileWriter(configs.ServerParams.StorageFile)
Сделал один кноструктор

2023-12-06 16:55 UTC, lev-stas commented
Тест падает. Я перезапускал несколько раз job-у, и падала то на 7-й итерации, то на 9-й. На 9-й из лога видно, что агент иногда не может отправить данные на сервер по причине недоступности последнего. Не знаю по какой причине такая ситуация возникает на тестировании. Локальные тесты проходят без проблем и не сервер не падает. Поэтому отправляю на ревью как есть, потому что уже "горю" по срокам.

2023-12-07 18:40 UTC, maxlyaptsev requested changes

2023-12-07 18:40 UTC, maxlyaptsev commented on internal/metricsstorage/filewriter.go
> +}
смысла не вижу в этом интерфейсе - во-первых интерфейсы описываются в месте где используются - т.е. там где требуется именно такая зависимость. А тут создает только лишнюю сложность

2023-12-07 21:08 UTC, lev-stas commented on internal/metricsstorage/filewriter.go
> +}
Избавился от интерфейса.

2023-12-07 21:11 UTC, lev-stas commented on internal/routers/rootrouter.go
> +	}
Я так с ходу не придумал выражение, которое будет пропускать /update/ , /update/gauge/{metricsName}/{metricsValue}, но при этом будет срабатывать на /update/wrongType/{metricsName}/{metricsValue}. Кажется, что упрощая обработчика, мы усложняем сам роутер.

2023-12-21 18:50 UTC, merged