Iter5
lev-stas/metricsmonitor pull request #6
Opened 2023-11-06 19:00 UTC by lev-stas

2023-11-07 16:31 UTC, maxlyaptsev requested changes

2023-11-07 16:31 UTC, maxlyaptsev commented on internal/memstorage/memstorage.go
> +type StorageInterface interface {
интерфейсы имеет смысл объявлять по месту использования т.к. тут утиная типизация и любой другой storage тоже сможет удовлетворить этому интерфейсу

2023-11-07 16:31 UTC, maxlyaptsev commented on internal/handlers/customMetricsUpdater.go
> +package handlers
имена файлов должны быть в нижнем регистре без тире и подчеркиваний (_test исключение)

2023-11-07 16:31 UTC, maxlyaptsev commented on cmd/agent/flags.go
> +package main
лучше работу с флагами вынести в отдельный пакет. И называть флагами было бы неверно - тут еще и из envs происходит чтение

2023-11-07 16:31 UTC, maxlyaptsev commented on cmd/agent/main.go
> +	"github.com/lev-stas/metricsmonitor.git/internal/handlers"
не логичная зависимость - агент, который отправляет метрики зависит от api ручек, это неправильно. Нужно подумтаь над структурой и определить пакет который будет отвечать за клиентский код. Это относится к handlers/vars.go, metricsPicker.go и т.д.

2023-11-07 16:31 UTC, maxlyaptsev commented on internal/routers/valueRouter.go
> +	r.Get("/{metricsType}/{metricsName}", handlers.ValueHandler(storage))
нет смысла дробить один роутер - лучше создать его один раз и объявить в нем все ручки:

```go
r := chi.NewRouter()
r.Get("/", handlers.RootHandler(storage))
r.Post("/{metricsType}/{metricsName}/{metricsValue}", handlers.HandleUpdate(storage))
r.Get("/{metricsType}/{metricsName}", handlers.ValueHandler(storage))
```

Сюда же будут добавляться и мидлвары впоследствии

2023-11-07 16:31 UTC, maxlyaptsev commented on internal/handlers/metricsPicker.go
> +			fieldValue := reflect.ValueOf(m).FieldByName(metricName)
рефлексию следует использовать только в ооочень крайних случаев, когда без этого действительно не обойтись. Почему - это большая нагрузка и все ошибки будут в рантайме, а не при компиляции

2023-11-07 16:31 UTC, maxlyaptsev commented on internal/handlers/reportRunner.go
> +	randomValueUrl := fmt.Sprintf("http://%s/update/gauge/RandomValue/%f", server, randomValue.RandomValue)
мы должны не при отправке генерировать рандомное число, а добавить его на этапе наполнения metrics. Аналогчно для каунтер. И соответственно можно не созадвать новый патерн для url. RandomValue это тоже metricName

2023-11-07 16:31 UTC, maxlyaptsev commented on internal/handlers/updateHandler.go
> +		if metricsType == "counter" {
`"counter"` и подобные строки лучше выносить либо в константы либо создавать новые типы (type MetricType string) чтобы пользоваться благами строгой типизации. Что угодно в go может стать типом, даже функция

2023-11-07 16:31 UTC, maxlyaptsev commented on cmd/agent/main.go
> +	}
nit: лучше тоже вынести в какой-то пакет где будет настройка и запуск

2023-11-10 17:44 UTC, lev-stas commented on internal/handlers/customMetricsUpdater.go
> +package handlers
fixed

2023-11-10 18:18 UTC, lev-stas commented on cmd/agent/flags.go
> +package main
Done

2023-11-10 18:46 UTC, lev-stas commented on cmd/agent/main.go
> +	}
Done

2023-11-10 20:14 UTC, lev-stas commented on cmd/agent/main.go
> +	"github.com/lev-stas/metricsmonitor.git/internal/handlers"
Done

2023-11-12 18:14 UTC, lev-stas commented on internal/routers/valueRouter.go
> +	r.Get("/{metricsType}/{metricsName}", handlers.ValueHandler(storage))
Done

2023-11-13 18:31 UTC, lev-stas commented on internal/routers/valueRouter.go
> +	r.Get("/{metricsType}/{metricsName}", handlers.ValueHandler(storage))
Done

2023-11-15 12:07 UTC, maxlyaptsev approved these changes

2023-11-16 13:38 UTC, merged